spring:
  application:
    name: test-graalvm

  # SQLite 数据库配置
  datasource:
    url: jdbc:sqlite:./demo.db
    driver-class-name: org.sqlite.JDBC

  # JPA/Hibernate 配置
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

